apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: prom-otel
data:
  collector.yaml: |
    receivers:
      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu: {}
          memory: {}
          network: {}
          load: {}
      prometheus:
        config:
          scrape_configs:
            - job_name: coredns
              scrape_interval: 15s
              static_configs:
                - targets: ["kube-dns.kube-system.svc.cluster.local:9153"]

    processors:
      cumulativetodelta: {}
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_mib: 200

    exporters:
      debug: {}
      otlphttp:
        endpoint: "http://prometheus.prom-otel.svc:9090/api/v1/otlp"
        tls:
          insecure: true
      prometheusremotewrite:
        endpoint: "http://prometheus.prom-otel.svc:9090/api/v1/write"
        tls:
          insecure: true
      otlp/newrelic:
        endpoint: "otlp.nr-data.net:4317"
        tls:
          insecure: false
        headers:
          api-key: ${env:NEW_RELIC_LICENSE_KEY}

    service:
      pipelines:
        # metrics/prometheus:
        #   receivers: [hostmetrics]
        #   processors: [memory_limiter, batch]
        #   exporters: [otlphttp, debug]
        metrics/prometheus-remote-write:
          receivers: [hostmetrics, prometheus]
          processors: [memory_limiter, batch]
          exporters: [prometheusremotewrite, debug]
        metrics/newrelic:
          receivers: [hostmetrics, prometheus]
          processors: [memory_limiter, cumulativetodelta, batch]
          exporters: [otlp/newrelic]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: prom-otel
  labels:
    app: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: docker.io/otel/opentelemetry-collector-contrib:latest
          args: ["--config=/etc/otel/collector.yaml"]
          env:
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic-license-key
                  key: licensekey
          volumeMounts:
            - name: config
              mountPath: /etc/otel
      volumes:
        - name: config
          configMap:
            name: collector-config
