apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prom-otel
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    storage:
      tsdb:
        out_of_order_time_window: 30m

    # otlp:
    #   translation_strategy: NoTranslation
    #   promote_resource_attributes:
    #     - service.name
    #     - service.namespace
    #     - service.instance.id
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prom-otel
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.enable-otlp-receiver
            - --web.enable-remote-write-receiver
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: storage
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prom-otel
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
