# Second instance of the same image, under a different service.name, tuned to
# be mostly non-compliant so the New Relic scorecard clearly flags it as a
# distinct, unhealthy entity next to the mostly-compliant orders-demo.
# Build/push the image exactly as for demo-app.yaml (see ../README.md), then:
#   kubectl create secret generic newrelic-license --from-literal=license-key="$NEW_RELIC_LICENSE_KEY"
#   kubectl apply -f demo-app/k8s/demo-app-noncompliant.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-demo-noncompliant
  labels:
    app: orders-demo-noncompliant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-demo-noncompliant
  template:
    metadata:
      labels:
        app: orders-demo-noncompliant
    spec:
      containers:
        - name: orders-demo-noncompliant
          image: bpschmitt/weaver-orders-demo:latest
          imagePullPolicy: Always
          args: ["--mode", "demo"]
          env:
            - name: OTEL_SERVICE_NAME
              value: orders-demo-noncompliant
            - name: ORDERS_PER_SEC
              value: "2"
            - name: NONCOMPLIANT_RATIO
              value: "0.6"
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic-license
                  key: license-key
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 200m, memory: 128Mi }
